from aiogram.dispatcher.filters.state import StatesGroup, State


class DoubleVizitState(StatesGroup):
    finishs = State()
    finish_vizit = State()
    finish = State()
    pharmacy_analysis = State()
    pharmacy_agreement_ = State()
    pharmacy_protest = State()
    pharmacy_presentation = State()
    pharmacy_the_need = State()
    pharmacy_preparation = State()
    pharmacy_communication = State()
    # pharmacy_preparation = State()
    search_or_submit_pharmacy = State()
    pharmacy_vizit = State()
    pharmacy_agreement = State()
    pharmacy_comment = State()
    address = State()
    create_pharmacy_city = State()
    create_pharmacy = State()
    pharmacy = State()
    pharmacy_city = State()
    analysis = State()
    agreement_ = State()
    protest = State()
    presentation = State()
    the_need = State()
    communication = State()
    preparation = State()
    agreement = State()
    checked = State()
    type = State()
    category = State()
    phone_number = State()
    comment = State()
    create_doctor = State()
    create_doct = State()
    doctor = State()
    create_hospital = State()
    lpu = State()
    create_city = State()
    city = State()
    search_or_submit = State()
    vizit = State()
    begin = State()

    @property
    def finish(self):
        return self._finish
