latin = {
    "REGISTER": "®️ Register",
    "LOGIN": "🔰 Login",
    "WAIT": "🔄 Yangilash",
    "LOCATION": "📍 Joylashuv",
    "VIZIT": "💷 Vizit",
    "KPI": "📊 KPI",
    "BRON": "💉 Buyurtmalar",
    "BRON_DELIVERY": "Ombor Buyurtmalar",
    "DOGOVOR": "🗞 Shartnoma Raqam",
    "QARZDORLIK": "💸 Qarzdorlik",
    "QARZDORLIK_AGENT": "💸 Qarzdorlik M/P",
    "SETTINGS": "⚙️ Sozlamalar",
    "PHONE_NUMBER": "📱 Telefon Raqam",
    "SEARCH": "🔍 Qidirish",
    "CREATE_ORDER": "➕ Yaratish",
    "UPDATE_ORDER": "❓ Tasdiqlanmagan",
    "BACK_MENU": "◀️ Orqaga",
    "DELETE_ORDER": "❌ Buyurtmani O'chirish",
    "SEND_OFFICE_MANAGER": "🏤 Offis menedjerga jo'natish",
    "ORDER_UPDATE_COMMENT_PRODUCTS": "↕️ Buyurtmaga o'zgartirish kiritish",
    "INN": "Korxona STIRI",
    'HOSPITAL_RESIDUE': '🏥 Dorixona Qoldig\'i',
    "COMMENT": "Izoh : ",
    "PREV": "⏮ Orqaga",
    "NEXT": "⏭ Oldinga",
    "EXIT": "⁉️ Chiqish",
    "NOT_FOUND": "Uzur ma'lumot topilmadi",
    "NAME": "Nomi",
    "COUNT": "Soni",
    "ADD_BASKET": "🗑 Savatga qo'shish",
    "CHOICE": "❌ Bekor qilish",
    'CHOICE_COUNT_UPDATE': 'Sonini kiriting ',
    "WELCOME": "Assalomu alaykum",
    "TO_THE": "Xush kelibsiz",
    "FIRST_NAME": "Ismingizni kiriting:",
    "LAST_NAME": "Familiyangizni kiriting: ",
    "LANGUAGE": "Tilni tanlang",
    "LATIN": "🇺🇿 O'zbek",
    "CYRIL": "🇺🇿 Ўзбекча",
    "RUSSIAN": "🇷🇺 Русский",
    "VILLAGE": "Viloyatingizni kiriting: ",
    "PHONE_NUMBER_SET": "Telefon nomeringizni kiriting:",
    "PASSWORD_IMAGE": "Passport rasmingizni kiriting png yoki img boshqa narsa kiritsangiz avtamatik tarzda o'chadi",
    "DATA_NOT_FOUND": "Hali ma'lumotlar bazasiga kiritmagan ekan ma'lum vaqtlardan keyin tekshirib ko'ring",
    "SUCCESSFULLY_REGISTERED": "Muaffaqiyatli registratsiyadan o'tdingiz",
    "BAD_PHONE_NUMBER": "Bunaqa nomer topilmadi boshidan urinib ko'ring",
    "BASE_MENU": "Bo'limga o'tishingiz mumkin",
    "CHOICE_PRODUCT": "Mahsulotlardan birini tanlang",
    "OR_THE_BACK": "Yoki orqaga chiqing",
    "THE_BACK": "Orqaga qaytishingiz mumkin",
    "THE_ONE_BACK": "Bitta orqaga qaytdik",
    'THE_ONE_NEXT': "Bitta oldinga o'tdik",
    "NO_ACTIVE": "⛔️ Aktiv emas",
    "YES_ACTIVE": "✅ Aktiv",
    "ORIGINAL_COUNT": "Original Soni",
    "CHOICE_COMPANY": "Korxonalardan birini tanlang",
    "CONTENT": "Tarkibi",
    "CAPACITY": "Sig'imi",
    "PRICE50%": "Narxi 50%",
    'PRICE100%': "Narxi 100%",
    'EXPIRATION_DATE': "Saqlash Muddati",
    "SERIA": "Seria",
    "CHOICE_COUNT": "Sonini kiriting(Qo'lda kiriting yoki shu yerdagilardan birini tanlang)",
    "BASE_MENU_BACK": "Bosh menuga qaytishingiz mumkin",
    "TOTAL_PRICE50%": "50% Umumiy Narxi",
    "TOTAL_PRICE100%": "100% Umumiy Narxi",
    "SAVE_BASKET": "Savatga qo'shishni xohlaysizmi ?",
    "CHOICE_REPLY": "Yana tanlashni xohlaysizmi ?",
    "CREATE_COMMENT": "Izox qoldirishingiz mumkin",
    "CREATE_INN": "Korxona STIR(INN)ni kiriting",
    "COMPANY_NAME": "Kompaniya nomi",
    "CREATE_COMPANY_NAME": "Korxona nomini kiriting",
    "CREATE_COMPANY_ADDRESS": "Korxona manzilini kiriting",
    "CREATE_COMPANY_INN": "Korxona INN(STIR)ni kiriting",
    "CREATE_COMPANY_PHONE_NUMBER": "Korxona telefonini kiriting",
    "CREATE_COMPANY_BANK_NAME": "Korxona homiy bankini kiriting",
    "ADDRESS": "Manzili",
    "COMPANY_PHONE": 'Kompaniya telefon raqami',
    "BANK": "Homiy bank",
    "CREATOR": 'Kim tomonidan',
    "SUM50%": "So'm(50%)",
    "SUM": "So'm",
    "SUM100%": "So'm(100%)",
    "DISTRICT": "Viloyat",
    "CITY": "Shahar(Tuman)",
    "INN_GET": "INN(STIR)",
    "COMMENT_GET": "Izoh ",
    'CREATED_DATE': "Yaratilgan Vaqt",
    "IS_AGREE": "Rozimisiz ?",
    "NO_SUCCESS": "Muvoffaqiyatli yakunlay olmadingiz !",
    'BASKET': '***Savatchada***',
    'PRICE': "Narxi",
    "SEND_MANAGER": "Buyurtmani offis menedjerga jo'natasizmi ? \nAgar buyurtmani offis menedjerga jo'natadigan bo'lsangiz buyurtmaga o'zgartirish kirita olmaysiz !",
    "SUCCESS": "Jarayon muvoffaqiyatli yakunlandi",
    'ADMIN_VIZIT_RESIDUE_SEE': '📁 Apteka Qoldiq Ekzel',
    "WELCOME_BRON": "Buyurtmalar bo'limiga xush kelibsiz",
    "CHOICE_UPDATE_ORDER": "Tahrirlamoqchi bo'lgan buyurtmangizni tanlang",
    "CHOICE_ORDER": "Tanlashingiz mumkin",
    'BASE_MENU_SEND': "Asosiy Bo'lim",
    "TOTAL_PRICE": "Ummumiy narx",
    "IS_SEND_OFFICE_MANAGER": "Buyurtmani agar offis menedjerga yuborsangiz keyin o'zgartira olmaysiz ! \nBuyurtmani jo'natasizmi?",
    'SUCCESS_SEND': "Muvoffaqiyatli yuborildi",
    "IS_DELETED": "O'chirishingizni tasdiqlaysizmi ?",
    "SUCCESS_DELETED": "Muvoffaqiyatli o'chirildi",
    "SUCCESS_UPDATED": "Muvoffaqiyatli o'zgartirildi",
    "VIZIT_MENU": "Vizit bo'limi",
    'SEND_LOCATION': "Iltimos manzilni jo‘nating faqat jonli tarzda jo‘natasiz ya’ni jonli joylashuvni (трансляция)",
    'CHOICE_VIZIT': "Tanlashingiz mumkin",
    'SUCCESS_LOCATION': "Joylashuv muvoffaqiyatli jo'natildi",
    "CITY_NAME": "Shahar nomini kiriting",
    "BACK": "Orqaga qaytishingiz mumkin",
    'LPU_CHOICE': "LPU lardan birini tanlang",
    'PHARMACY_CHOICE': "Dorixonalardan birini tanlang",
    "NOT_FOUND_LPU": "LPU nomini kiriting chunki sizda hali LPU yoq",
    "NOT_FOUND_PHARMACY": "Dorixona nomini kiriting chunki sizda hali Dorixona yoq",
    'CREATE_HOSPITAL': "LPU nomini kiriting",
    'CREATE_PHARMACY': "Dorixona nomini kiriting",
    'CHOICE_DOCTOR': "Doktorlardan birini tanlang",
    "OR_SEARCH": "Yoki qidirishingiz mumkin",
    "SUCCESS_CITY": "Shahar Muvoffaqiyatli qo'shildi",
    "CHOICE_CITY": "Shaharlardan birini tanlang",
    "SUCCESS_LPU": "LPU Muvoffaqiyatli qo'shildi",
    "SUCCESS_PHARMACY": "Dorixona Muvoffaqiyatli qo'shildi",
    "FIO_DOCTOR": "Iltimos do'ktorni familiyasi ismi va sharfini kiriting (FIO) iltimos to'liq bo'lsin masalan Zokirov Dilshod Zoirovich(Зокиров Дилшод Зоирович)",
    "DOCTOR_PHONE": "Doktorni telefon nomerini kiriting",
    'TYPE_DOCTOR': "Doktorni lavozimini  tanlang",
    "DOCTOR_CATEGORY": "Doktorni tipini tanlang",
    'DOCTOR_FAMILY_NAME': "Doktor ism familiyasi :",
    "GET_CATEGORY": "Doktor mutaxasisligi :",
    "TYPE_GET": "Doktor kategoriyasi:",
    "DOCTOR_PHONE_NUMBER": "Doktor telefon raqami",
    "HOSPITAL": "Kasalxona",
    "PHARMACY": "Dorixona",
    "MANAGER_VIZIT": "Doktor",
    "IS_AGREE_HOSPITAL": "Yaratilishiga rozimisiz ?",
    "DOCTOR_SUCCESS_CREATE": "Doktor muvoffaqiyatli qo'shildi",
    "DOCTOR_NAME": "Doktor",
    "SUCCESSFULLY": "Jarayon muvoffaqiyatli yakunlandi",
    "SEARCH_DOCTOR": "Qidirayotgan do'ctorni ismi yoki familiyasi yoki sharfini boshlanishini kiriting misol uchun (abd==Abdullayev)",
    "NEW_CREATE": "➕ Yangi Qo'shish",
    "SETTINGS_MENU": "Sozlamalar bo'limi",
    "LANGUAGE_BUTTON": "Tilni tahrirlash",
    "USER_INFORMATION": "Ma'lumotlarni tahrirlash",
    "VIZIT_REPORT": "Vizit Hisobotlari",
    "ADMIN_VIZIT_REPORT": "M/P Vizit Hisobotlari",
    "BRON_REPORT": "Buyurtma Hisobotlari",
    "BRON_REPORT_MESSAGE": "Buyurtmalar Hisoboti bo'limi",
    "VIZIT_REPORT_MESSAGE": "Vizit Hisoboti bo'limi",
    "MONTHS_CHOICE": "Oylardan birini tanlang",
    "DOCUMENT_FILE": "Fayl ko'rinishidagi Hisobotlar",
    "GEOLOCATION_DOCUMENT": "Joylashuv Hisobotlari",
    "MEMBER_LIST": "Ishchilardan birini tanlang",
    "EMPLOYED": "Ishchilar Ro'yxati",
    "NEW_EMPLOYED": "Arizalar",
    "NEW_EMPLOYED_MENU": "Arizalar bo'limi",
    "EMPLOYED_MENU": "Ishchilar bo'limi",
    "ROLES_MEMBER": "Marhamat lavozimiga mos barcha ishchilar",
    "MEMBER_NOT_FOUND": "Ishchilar topilmadi",
    "LIST_MEMBER": "Ishchilar ro'yhati",
    "CREATE_ROLE": "Lavozim Tanlash",
    "PENDING_UPDATE": "O'zgartirishni tasdiqlaysizmi ?",
    "CHOICE_ROLE": "Lavozimlardan birini tanlang !",
    "DELETE_MEMBER_CHECK": "Ishdan olishni tasdiqlang ?",
    "ROLE": "Lavozimi",
    "UPDATE_ROLE": "Lavozimni Tahrirlash",
    "DELETE_EMPLOYED": "Ishdan olish",
    "NAME_USER": "FIO",
    "PRODUCTS": "🔶 Maxsulotlar",
    "WAREHOUSE": "📩 Buyurtmalar",
    "INCOME": "📬 Tushum",
    "INCOME_AGENT": "📬 Tushum M/P",
    "DEBIT_MENU": "Qarzdorlik bolimi",
    "ORDERS_MENU": "Buyurtmalar bo'limi",
    "WAREHOUSE_MENU": "Buyurtmalar bo'limi",
    "CONTRACT_NUMBER_MENU": "Shartnoma raqam olish bo'limi",
    "INCOME_MENU": "Tushum bo'limi",
    'EXCEL_FORMAT': "Ekcel fayl ko'rinishida",
    'TEXT_FORMAT': "Text ko'rinishida",
    "HOME_BACK": "🏘 Asosiy Menu",
    "CREATE_PRODUCT": "➕ Qo'shish",
    "GET_ALL_PRODUCT": "↙️ Barcha maxsulotlar",
    "EDIT_PRODUCT": "📝 Tahrirlash",
    "DELETE_PRODUCT": "🗑 O'chirish",
    'CREATE_PRODUCT_NAME': "Maxsulot nomi kiriting ",
    "CREATE_PRODUCT_CONTENT": "Maxsulot tarkibi ",
    "CREATE_PRODUCT_PRICE50%": "Maxsulot narxi(50%) Faqat son ko'rinishda kiriting masalan(50000 yoki 5000.500) bo'lmasa o'chadi ",
    "CREATE_PRODUCT_PRICE100%": "Maxsulot narxi(100%)",
    "CREATE_PRODUCT_ORIGINAL_COUNT": "Original qadoqdagi soni ",
    "CREATE_PRODUCT_EXPIRATION_DATE": "Yarqolilik muddati(Faqat shu ko'rinishda yyyy-mm-dd misol 2026-12-31)",
    "CREATE_PRODUCT_SERIA": "Seria Raqami",
    "CREATE_PRODUCT_STATUS": "Status",
    "CREATE_PRODUCT_THE_REST": "Qoldiq(Skladda bor)",
    "CREATE_PRODUCT_IMAGE": "Maxsulot rasmi",
    "VIZIT_FILE": "Fayl ko'rinishida(Oylik hisobida)",
    "VIZIT_TEXT": "Xarita Ko'rinishida(Kunlik)",
    "VIZIT_LOCATION_TEXT": "Joylashuv bo'limiga kirdingiz",
    "DAY": "Qaysi kunnikini ko'rmoqchisiz ?",
    "LOCATION_USER": "Ishchining joylashuvlari",
    "GET_ALL_PRODUCT_TEXT": "Barcha maxsulotlarni ko'rishingiz mumkin",
    "STATUS": "Status",
    "HOW_PARAMETER_UPDATE": "Qaysi parameterlarini o'zgartirmoqchisiz ?",
    "UNDER_REPAIR": "Bu bo'lim hozircha ishlamayabdi",
    "BUY_CONTRACT_NUMBER": "Shartnoma raqam olish",
    "GET_CONTRACT_NUMBER": "Shartnoma raqam izlash",
    "SET_INN": "INN kiriting",
    "UPDATE_CONTRACT_NUMBER": "Marxamat shartnoma raqamingiz",
    "CURRENT_COMPANY_CHOICE_CONTRACT_NUMBER": "Shu buyurtma boyicha shartoma olmoqchimisiz ?",
    "CONTRACT_NUMBER_CREATED_AT": "Shartnoma berilgan vaqti",
    "CONTRACT_NUMBER": "Shartnoma raqami",
    "ERROR_INN": "Bunaqa inn ga shartnoma berilgan yoki berib bolmaydi topilmadi boshidan urinib ko'ring",
    "SET_INN_OR_CONTRACT_NUMBER": "INN kiriting",
    "BRON_DELIVERY_MENU": "Omborxona Bururtmalari bo'limiga xush kelibsiz buyurtmalardan birini tanlang",
    "SUBMIT": "Tasdiqlash",
    "PRODUCT_NO_ACTIVE": "Maxsulot aktiv emas",
    "YES": "Ha",
    "NO": "Yo'q",
    "DOUBLE_VIZIT": "Vizit",
    "DOCTOR_TYPE": "Kasbi",
    "HOW_TO_UPDATE_FIELD": "O'zgartirmoqchi bo'lgan parameteringizni tanlang",
    "UPDATE_COMMENT": "Izoh",
    "UPDATE_PRODUCT": "Maxsulot",
    "NEW_PRODUCT_OR_DELETE": "Yangi maxsulot qo'shsizmi yoki o'chirasizmi ?",
    "NEW_PRODUCT_CREATE": "Yangi maxsulot",
    "BAD_LOCATION": "Davom etish uchun iltimos jonli joylashuvni jo'nating (трансляция)",
    'HOW_TO_BAD_LOCATION': "Siz pastdagi 'Joylashuv' menyusini bosmadingiz",
    "CREATE_VILLAGE": "Ko'rayotgan viloyatni tanlang",
    "ADMIN_CREATE_VILLAGE": "Ixtiyoriy birini tanlang",
    'BRON_SUPPLIER': "Tasdiqlanmagan buyurtmalar",
    'CONFIRMED_ORDERS': "Tasdiqlangan",
    'UNREVIEWED_ORDERS': 'Tasdiqlanmagan',
    'BY_PROVINCES': "Viloyatlar Bo'yicha",
    'BY_WORKERS': "MP/Menedjer",
    'CONFIRMED_ORDERS_TEXT': "Tasdiqlangan buyurtmalardan birini tanlang",
    "UNREVIEWED_ORDERS_TEXT": "Tasdiqlanmagan buyurtmalardan birini tanlang",
    "NEW_DOCTOR_CREATE": "Yangi doktor kiriting",
    'EXCEL_CREATE': "📩 Maxsulot rejasi",
    'CREATE_EXCEL_TEXT': "Iltimos har oyning oxirida yangi reja excelini tashlab turing chunki bu yerda bir excel tashlagandan keyin keyingi excel tashlangancha bo'lgan ma'lumotlar saqalanadi excel kiriting boshqa ma'lumot o'chib ketadi",
    "CREATE_DEBIT_TEXT": "Qarzdorlik  excelini tashlang",
    "CREATE_INCOME_TEXT": "Tushum  excelini tashlang",
    'BAD_EXCEL': "Siz excel file kiritmadingiz",
    'ORDER_EXCEL_NOT_FOUND': "Iltimos sotuv rejasini tashlashini kutib turing Offis Menedjerni ogohlantiring agar tashlagan bo'lsa kutib turing",
    'BAG_FACTURE': "facture.uz da muommo bo'ldi iltimos to'g'irlanguncha qo'lda kiritib turing kompaniya nomini kiriting",
    "AGENT": "Agent(M/P)",
    "MANAGER": "Menedjer",
    "NOT_FOUND_WAREHOUSE_PRODUCT": "Omborda buncha maxsulot yo'q boshidan kiriting",
    "HOSPITAL_OR_VIZIT": "Dorixona yoki vizit birortasini tanlang",
    'MANAGER_FOR_CREATE': "M/P bilan birgalikda vizit qilasizmi",
    "CHOICE_MANAGER": "Iltimos ixtiyoriy birini tanlang yoki ismi orqali qidirishingiz mumkin",
    'CREATE_ADDRESS': "Mo'ljalni kiriting",
    'PREPARATION': "Tayyorgarlik",
    'COMMUNICATION': "Muloqot",
    'THE_NEED': "Ehtiyoj",
    'PRESENTATION': 'Taqdimot',
    "PROTEST": "Etiroz",
    'AGREEMENT': "Kelishuv",
    'ANALYSIS': 'Tahlil',
    'EVALUATION': "Оценить",
    'PHARMACY_NAME': "Dorixona Nomi",
    "TEST_EXCEL": "Meneger Xisoboti",
    "GET_ALL_ORDERS_AGENT": "↙️ Mening buyurtmalarim",
    "GET_ALL_TEXT": "Marxamat tasdiqlangan yoki tasdiqlanmagan buyurtmalar ixtiyoriy birini tanlang",
    "CONFIRMED_AGENT_ORDERS": "✅ Tasdiqlangan",
    "UNCONFIRMED_AGENT_ORDERS": "❓ Tasdiqlanmagan",
    'NOT_CONFIRMED_TEXT': "Tasdiqlanmagan buyurtmalar",
    "CONFIRMED_TEXT": "Tasdiqlangan buyurtmalar",
    'NAME_MEMBER': "F.I.SH",
    "MEMBER_PHONE": "Telefon raqami",
    'DISTRICT_UPDATE': "Viloyatini taxrirlash",
    'UPDATE_USER_DATA': 'Ismni tahrirlash',
    'UPDATE_PHONE_NUMBER': 'Telefon nomerini tahrirlash',
    'CREATE_USER_PHONE_NUMBER': "Telefon raqamni kiriting",
    'CREATE_USER_NAME': "Ishchining ismini kiriting",
    'CREATE_USER_LAST_NAME': "Ishchining familyasini kiriting",
    "NOT_PLUS": "Raqamni '+' belgisi bilan boshlang misol uchun +998900123456 qaytadan urinib ko'ring",
    "NOT_LENGTH": "Kiritayotgan belgingiz 13 ta belgidan iborat emas boshidan urinib ko'ring",
    'NOT_INT': "Siz boshqa ma'lumotlar kiritayabsiz iltimos to'g'ri ma'lumot kiriting",
    'VIZIT_DOCUMENT_MANAGER_TEXT': "Joylashuv yoki Vizit xisobotlari birini tanlang",
    'MANAGER_DOCUMENT': 'Vizit Hisoboti',
    'MANAGER_LOCATION': 'Joylashuv Hisoboti',
    'WORKERS': "Ishchilar ro'yxati",
    'UPDATE_USER_DATA_LAST_NAME': 'Familiyani tahrirlash',
    'BAD_REQUEST_PRODUCT': "Omborda buncha maxsulot yo'q qaytadan urinib ko'ring",
    'OFFICE_MANAGER_CONTRACT_NUMBER_EXCEL': "📃 Shartnoma Raqam",
    'FILE_NOT_FOUND': "Fayl topilmadi",
    'READ_OR_CREATE': "Yangisini qo'shish yoki yuklashni xohlaysizmi ?",
    'CREATE_CONTRACT_NUMBER': "Eksel Yaratish",
    'READ_CONTRACT_NUMBER': 'Eksel Yuklash',
    'CREATE_CONTRACT_NUMBER_TEXT': 'Shartnoma raqam ekselini tashlang',
    'NOT_FOUND_PRODUCT': 'Maxsulot topilmadi iltimos offis menedjerga ayting maxsulot qo\'shsin',
    'CREATE_DIRECTOR_NAME': 'Korxona(Dorixona) boshlig\'ini ism familiyasini kiriting',
    'CREATE_PROVIDER_PHONE_NUMBER': 'Korxona (Dorixona) boshlig\'i yordamchisini telefon nomeringi kiriting',
    'CREATE_DIRECTOR_PHONE_NUMBER': 'Korxona (Dorixona) boshlig\'ini telefon nomeringi kiriting',
    'CREATE_PROVIDER_NAME': 'Korxona (Dorixona) boshlig\'i yordamchisini ism familiyasini kiriting',
    'DIRECTOR_NAME': "Direktor ismi",
    'DIRECTOR_PHONE_NUMBER': "Direktor telefon raqami",
    'PROVIDER_NAME': "Yordamchi ismi",
    'PROVIDER_PHONE_NUMBER': "Yordamchi telefon raqami",
    'CHECK_CREATE_BOSSES': 'Ma\'lumotlar to\'g\'rimi ?',
    'CANCEL_BOSSES_UPDATED': 'O\'zgartirilmadi siz rad javobini berdingiz',
    'SUCCESS_BOSSES_UPDATED': 'Korxona (Dorixona) boshliqlari ma\'lumotlari muaffaqiaytli o\'zgartirildi',
    "BAD_REQUEST": "Iltimos to'g'ri ma'lumot kiriting son kiritmaguncha to'g'ri ishlaymaydi",
    'EXCEL_FILE': 'Marxamat eksel faylni ko\'rishingiz mumkin',
    'NOT_FOUND_EXCEL_FILE': "Fayl hozirda yuklanmoqda iltimos 5 daqiqadan keyin urinib ko'ring",
    'HOSPITAL_PARAMS': '🏥 Dorixona Qoldiq',
    'CHOICE_EXCEL_OR_HOSPITAL_VIZIT_RESIDUE': 'Eksel yoki qoldiq kiritmoqchimisiz ?',
    'EXCEL_PATH': 'Eksel fayl yuklash',
    'EXCEL_TEXT': 'Dorixona qoldiq kiritish',
    'NOT_FOUND_PRODUCT_OFFICE': 'Maxsulot topilmadi',

}
russian = {
    'NOT_FOUND_PRODUCT_OFFICE': 'Товар не найден',
    'EXCEL_PATH': 'Загрузка файла Excel',
    'EXCEL_TEXT': 'Ввод баланса аптеки',
    'ADMIN_VIZIT_RESIDUE_SEE': '📁 Аптечный остаток Excel',
    'HOSPITAL_PARAMS': '🏥 Аптечный остаток',
    'CHOICE_EXCEL_OR_HOSPITAL_VIZIT_RESIDUE': 'Хотите войти в Excel или баланс ?',
    'NOT_FOUND_EXCEL_FILE': "Файл сейчас загружается, повторите попытку через 5 минут.",
    "HOME_BACK": "🏘 Главное меню",
    "REGISTER": "®️ Регистер",
    "LOGIN": "🔰 Логин",
    "WAIT": "🔄 Обновлять",
    "LOCATION": "📍 Расположение",
    "VIZIT": "💷 Визит",
    "KPI": "📊 КПИ",
    "BRON": "💉 Брон",
    "DOGOVOR": "🗞 Номер контракта",
    "QARZDORLIK": "💸 Задолженность",
    "QARZDORLIK_AGENT": "💸 Задолженность М/П",
    "SETTINGS": "⚙️ Настройки",
    "PHONE_NUMBER": "📱 Номер телефона",
    "SEARCH": "🔍 Поиск",
    "CREATE_ORDER": "➕ Создавать",
    "UPDATE_ORDER": "❓ Не подтверждено",
    "BACK_MENU": "◀️ Назад",
    "DELETE_ORDER": "❌ Удалить заказ",
    "SEND_OFFICE_MANAGER": "🏤 Отправить офис-менеджеру",
    "ORDER_UPDATE_COMMENT_PRODUCTS": "↕️ Внесение изменений в заказ",
    'CHOICE_COUNT_UPDATE': 'Введите номер',
    "INN": "ИНН предприятия",
    "COMMENT": "Объяснение",
    'HOSPITAL_RESIDUE': '🏥 Аптечный остаток',
    "PREV": "⏮ Позади",
    "NEXT": "⏭ Вперед",
    "EXIT": "⁉️ Выход",
    "NOT_FOUND": "Извините, но информация не найдена",
    "NAME": "Имя",
    "COUNT": "Число количество",
    "ADD_BASKET": "🗑 Добавить в корзину",
    "CHOICE": "Отмена заказа",
    "WELCOME": "Привет",
    "TO_THE": "добро пожаловать",
    "FIRST_NAME": "Пожалуйста, введите Ваше имя:",
    "LAST_NAME": "Пожалуйста, введите свою фамилию: ",
    "LANGUAGE": "Пожалуйста, выберите язык:",
    "LATIN": "🇺🇿 Латин узбекский",
    "CYRIL": "🇺🇿🇷🇺 Криль узбекский",
    "RUSSIAN": "🇷🇺 Русский",
    "VILLAGE": "Пожалуйста, введите ваш регион:",
    "PHONE_NUMBER_SET": "Введите свой номер телефона:",
    "PASSWORD_IMAGE": "Пожалуйста, введите фото своего паспорта, png или img будут удалены автоматически, если вы введете что-либо еще",
    "DATA_NOT_FOUND": "Извините, но вы еще не добавлены в базу данных, поэтому, пожалуйста, зайдите через некоторое время.",
    "SUCCESSFULLY_REGISTERED": "Вы успешно зарегистрировались",
    "BAD_PHONE_NUMBER": "К сожалению, такой номер не найден, попробуйте еще раз",
    "BASE_MENU": "Пожалуйста, смело переходите в раздел",
    "CHOICE_PRODUCT": "Пожалуйста, выберите один из продуктов",
    "OR_THE_BACK": "Или вернуться",
    "THE_BACK": "Пожалуйста, вернитесь",
    "THE_ONE_BACK": "Спасибо, мы вернулись один",
    'THE_ONE_NEXT': "Спасибо, мы продвинулись вперед",
    "NO_ACTIVE": "Не активен",
    "YES_ACTIVE": "Активный",
    "ORIGINAL_COUNT": "Исходный номер",
    "CONTENT": "Состав",
    "CAPACITY": "Емкость",
    "PRICE50%": "Расходы 50%",
    'PRICE100%': "Расходы 100%",
    'EXPIRATION_DATE': "Употребить до",
    "SERIA": "Серии",
    "CHOICE_COUNT": "Введите номер (введите вручную или выберите один здесь)",
    "BASE_MENU_BACK": "Введите число",
    "TOTAL_PRICE50%": "50% Итоговая цена",
    "TOTAL_PRICE100%": "100% Итоговая цена",
    "SAVE_BASKET": "Хотите добавить в корзину ?",
    "CHOICE_REPLY": "Вы хотите выбрать снова ?",
    "CREATE_COMMENT": "Вы можете оставить комментарий",
    "CREATE_INN": "Пожалуйста, введите СТИРИ(ИНН) предприятия",
    "COMPANY_NAME": "Название компании",
    "ADDRESS": "Адрес",
    "COMPANY_PHONE": 'Номер телефона компании',
    "BANK": "Банк-спонсор",
    "CREATOR": 'Кем',
    "SUM50%": "сум(50%)",
    "SUM": "сум",
    "SUM100%": "сум(100%)",
    "DISTRICT": "Область",
    'OFFICE_MANAGER_CONTRACT_NUMBER_EXCEL': "📃 Номер контракта",
    "CITY": "Город(Район)",
    "INN_GET": "ИНН(СТИР)",
    "COMMENT_GET": "Комментарий",
    'CREATED_DATE': "Время создания",
    "IS_AGREE": "Вы согласны?",
    "NO_SUCCESS": "Вы не смогли успешно завершить",
    'BASKET': '*****В корзине*****',
    'PRICE': "Расходы",
    "SEND_MANAGER": "Вы отправите заказ офис-менеджеру? Если вы отправляете заказ офис-менеджеру, вы не можете вносить изменения в заказ!",
    "SUCCESS": "Процесс успешно завершен",
    "WELCOME_BRON": "Добро пожаловать в меню бронирования",
    "CHOICE_UPDATE_ORDER": "Выберите заказ, который хотите изменить",
    "CHOICE_ORDER": "Ты можешь выбрать",
    'BASE_MENU_SEND': "Спасибо главное меню",
    "TOTAL_PRICE": "Итоговая цена",
    "IS_SEND_OFFICE_MANAGER": "Вы уверены, что если вы отправите его офис-менеджеру, вы не сможете изменить его позже?",
    'SUCCESS_SEND': "Успешно отправлено",
    "IS_DELETED": "Вы уверены, что хотите удалить?",
    "SUCCESS_DELETED": "Удалено успешно",
    "SUCCESS_UPDATED": "Изменено успешно",
    "VIZIT_MENU": "Спасибо за посещение меню",
    'SEND_LOCATION': "Пожалуйста, пришлите адрес, вы будете отправлять его только в прямом эфире, то есть в прямом эфире.",
    'CHOICE_VIZIT': "Вы можете свободно выбирать",
    'SUCCESS_LOCATION': "Успешное местоположение отправлено",
    "CITY_NAME": "Введите название города",
    "BACK": "Вы можете вернуться",
    'LPU_CHOICE': "Выберите один из LPU",
    'PHARMACY_CHOICE': "Выберите одну из аптек",
    "NOT_FOUND_LPU": "Пожалуйста, введите имя LPU, потому что у вас все еще есть LPU",
    "NOT_FOUND_PHARMACY": "Введите название аптеки, потому что у вас все еще есть аптека",
    'CREATE_HOSPITAL': "Пожалуйста, введите название докторской степени",
    'CREATE_PHARMACY': "Введите название аптеки",
    'CHOICE_DOCTOR': "Выбрать одного из врачей",
    'PHARMACY_NAME': "Название аптеки",
    "OR_SEARCH": "Или вы можете искать",
    "SUCCESS_CITY": "Город успешно добавлен",
    "CHOICE_CITY": "Выберите один из городов",
    "SUCCESS_LPU": "LPU успешно добавлен",
    "SUCCESS_PHARMACY": "Аптека успешно добавлена",
    "FIO_DOCTOR": "Пожалуйста, введите ФИО врача (ФИО), например, Зокиров Дилшод Зойрович (Zokirov Dilshod Zoirovich), иначе может возникнуть недоразумение.",
    "DOCTOR_PHONE": "Пожалуйста, введите номер телефона врача",
    'TYPE_DOCTOR': "Пожалуйста, выберите должность врача, например Уролог",
    "DOCTOR_CATEGORY": "Пожалуйста, выберите тип врача, например C",
    'DOCTOR_FAMILY_NAME': "Имя доктора :",
    "GET_CATEGORY": "Специальность врача",
    "TYPE_GET": "Категория доктора :",
    "DOCTOR_PHONE_NUMBER": "Номер телефона доктора",
    "HOSPITAL": "Больница",
    "IS_AGREE_HOSPITAL": "Вы согласны быть созданным?",
    "DOCTOR_SUCCESS_CREATE": "Доктор присоединился успешно",
    "DOCTOR_NAME": "Врач",
    "SUCCESSFULLY": "Процесс успешно завершен",
    "SEARCH_DOCTOR": "Пожалуйста, введите имя или фамилию врача, которого вы ищете, например (абд==Абдуллаев и т.д.)",
    "NEW_CREATE": "➕ Добавить новое",
    "SETTINGS_MENU": "Добро пожаловать в раздел настроек!!",
    "LANGUAGE_BUTTON": "Изменить язык",
    "USER_INFORMATION": "Редактирование данных",
    "VIZIT_REPORT": "Отчеты о посещениях",
    "BRON_REPORT": "Отчеты о заказах",
    "BRON_REPORT_MESSAGE": "Добро пожаловать в раздел Отчет о заказах",
    "VIZIT_REPORT_MESSAGE": "Добро пожаловать в раздел Отчет о посещении",
    "MONTHS_CHOICE": "Выберите один из месяцев",
    "DOCUMENT_FILE": "Отчеты в представлении файлов",
    "GEOLOCATION_DOCUMENT": "Отчеты о местоположении",
    "MEMBER_LIST": "Пожалуйста, выберите одного из работников",
    "EMPLOYED": "Список рабочих",
    "NEW_EMPLOYED": "Приложения",
    "NEW_EMPLOYED_MENU": "Добро пожаловать в раздел Приложения",
    "EMPLOYED_MENU": "Добро пожаловать в раздел персонала",
    "ROLES_MEMBER": "Приветствуются все сотрудники, подходящие для этой роли",
    "MEMBER_NOT_FOUND": "Извините, но рабочих не найдено",
    "LIST_MEMBER": "Список рабочих пожалуйста",
    "CREATE_ROLE": "Выбор позиции",
    "PENDING_UPDATE": "Вы уверены, что хотите измениться ?",
    "CHOICE_ROLE": "Пожалуйста, выберите одну из позиций!",
    "ROLE": "Позиция",
    "UPDATE_ROLE": "Изменить позицию",
    "DELETE_EMPLOYED": "Увольнение",
    "NAME_USER": "ФИО",
    "DELETE_MEMBER_CHECK": "Вы уверены, что хотите, чтобы вас уволили ?",
    "PRODUCTS": "🔶 Продукты",
    "WAREHOUSE": "📩 Заказы",
    "INCOME": "📬 Поступления",
    "INCOME_AGENT": "📬Поступления М/П",
    "DEBIT_MENU": "Добро пожаловать в раздел долгов",
    "ORDERS_MENU": "Добро пожаловать в раздел Заказы",
    "WAREHOUSE_MENU": "Добро пожаловать в отдел склада",
    "INCOME_MENU": "Добро пожаловать в раздел доходов",
    "CREATE_PRODUCT": "➕ Добавить",
    "GET_ALL_PRODUCT": "↙️ Все продукты",
    "EDIT_PRODUCT": "📝 Редактировать",
    "DELETE_PRODUCT": "🗑 Удалить",
    'CREATE_PRODUCT_NAME': "Введите название продукта",
    "CREATE_PRODUCT_CONTENT": "Состав продукта",
    "CREATE_PRODUCT_PRICE50%": "Цена продукта (50%)",
    "CREATE_PRODUCT_PRICE100%": "Цена продукта (100%)",
    "CREATE_PRODUCT_ORIGINAL_COUNT": "Номер в оригинальной упаковке",
    "CREATE_PRODUCT_EXPIRATION_DATE": "Дата истечения срока действия",
    "CREATE_PRODUCT_SERIA": "Серийный номер",
    "CREATE_PRODUCT_STATUS": "Положение дел",
    "CREATE_PRODUCT_THE_REST": "Остаток(в наличии)",
    "CREATE_PRODUCT_IMAGE": "Изображение продукта",
    "VIZIT_FILE": "Просмотр файлов (ежемесячный счет)",
    "VIZIT_TEXT": "В режиме просмотра карты (ежедневно)",
    "VIZIT_LOCATION_TEXT": "Вы вошли в раздел местоположения",
    "DAY": "Какой день вы хотите увидеть ?",
    "LOCATION_USER": "Местонахождение работника",
    "GET_ALL_PRODUCT_TEXT": "Вы можете посмотреть все товары",
    "STATUS": "Положение дел",
    "HOW_PARAMETER_UPDATE": "Какие параметры вы хотите изменить ?",
    "UNDER_REPAIR": "Этот раздел находится на ремонте",
    "CONTRACT_NUMBER_MENU": "Отдел нумерации договоров",
    "BUY_CONTRACT_NUMBER": "Получить номер договора",
    "GET_CONTRACT_NUMBER": "Поиск по номеру договора",
    "SET_INN": "Введите ИНН",
    "UPDATE_CONTRACT_NUMBER": "Спасибо за номер договора",
    "CURRENT_COMPANY_CHOICE_CONTRACT_NUMBER": "Вы хотите получить контракт на этот заказ ?",
    "CONTRACT_NUMBER_CREATED_AT": "Время действия контракта",
    "CONTRACT_NUMBER": "Контактный номер",
    "ERROR_INN": "Эта гостиница получила контракт или не может быть найдена. Повторите попытку.",
    "SET_INN_OR_CONTRACT_NUMBER": "Введите ИНН",
    "BRON_DELIVERY": "Складские заказы",
    "BRON_DELIVERY_MENU": "Добро пожаловать в раздел Складские заказы и выберите один из заказов",
    "SUBMIT": "Подтвердить",
    "PRODUCT_NO_ACTIVE": "Товар не активен",
    "YES": "Да",
    "NO": "Нет",
    "HOW_TO_UPDATE_FIELD": "Выберите параметр, который хотите изменить",
    "UPDATE_COMMENT": "Комментарий",
    "UPDATE_PRODUCT": "Продукт",
    "NEW_PRODUCT_OR_DELETE": "Добавить или удалить новый продукт ?",
    "NEW_PRODUCT_CREATE": "Новый продукт",
    "BAD_LOCATION": "Пожалуйста, отправьте текущее местоположение, иначе оно исчезнет",
    'HOW_TO_BAD_LOCATION': "Вы не нажали на меню «Местоположение» внизу",
    "CREATE_VILLAGE": "Выберите интересующий вас регион",
    "ADMIN_CREATE_VILLAGE": "Выберите дополнительный",
    'NOT_FOUND_PRODUCT': 'Товар не найден, сообщите менеджеру офиса, чтобы он добавил товар',
    'BRON_SUPPLIER': "Заказы поставщика",
    'CONFIRMED_ORDERS': "Подтвержденный",
    'UNREVIEWED_ORDERS': 'Не подтверждено',
    'BY_PROVINCES': "По регионам",
    'BY_WORKERS': "МП/Менеджер",
    'CONFIRMED_ORDERS_TEXT': "Выберите один из подтвержденных заказов",
    "UNREVIEWED_ORDERS_TEXT": "Выберите один из неподтвержденных заказов",
    "NEW_DOCTOR_CREATE": "Введите нового врача",
    'EXCEL_CREATE': "📩 План продукта",
    'CREATE_EXCEL_TEXT': "Пожалуйста, оставляйте новый план excel в конце каждого месяца, потому что после выхода из одного excel данные до следующего excel удаляются.Введите excel, другая информация будет удалена",
    "CREATE_DEBIT_TEXT": "Сбросить долг excel",
    "CREATE_INCOME_TEXT": "Выкинуть доход excel",
    'BAD_EXCEL': "Вы не вставили файл Excel",
    'ORDER_EXCEL_NOT_FOUND': "Пожалуйста, подождите, пока план будет удален. Сообщите офис-менеджеру, если он будет удален. Пожалуйста, подождите",
    'EXCEL_FORMAT': "В представлении Excel",
    'TEXT_FORMAT': "В текстовом виде",
    "CHOICE_COMPANY": "Выберите одну из компаний",
    "CREATE_COMPANY_NAME": "Введите название компании",
    "CREATE_COMPANY_ADDRESS": "Введите адрес вашей компании",
    "CREATE_COMPANY_INN": "Введите СТИР предприятия",
    "CREATE_COMPANY_PHONE_NUMBER": "Введите номер вашего рабочего телефона",
    "CREATE_COMPANY_BANK_NAME": "Войти в корпоративный банк-спонсор",
    'BAG_FACTURE': "Возникла проблема с facture.uz, введите название компании вручную, пока проблема не будет устранена",
    "AGENT": "Агент(М/П)",
    "MANAGER": "Менеджер",
    "NOT_FOUND_WAREHOUSE_PRODUCT": "На складе не так много товаров, вводите с начала",
    "DOUBLE_VIZIT": "Визит",
    "HOSPITAL_OR_VIZIT": "Выберите либо аптеку, либо визит",
    "PHARMACY": "Аптека",
    "MANAGER_VIZIT": "Врач",
    'MANAGER_FOR_CREATE': "Вы приедете вместе с M/P ?",
    "CHOICE_MANAGER": "Пожалуйста, выберите необязательный или вы можете искать по имени",
    'CREATE_ADDRESS': "Введите пункт назначения",
    'PREPARATION': "Подготовка",
    'COMMUNICATION': "Коммуникация",
    'THE_NEED': "Нуждаться",
    'PRESENTATION': 'Презентация',
    "PROTEST": "Протест",
    'AGREEMENT': "Дагавор",
    'ANALYSIS': 'Анализ',
    'EVALUATION': "Оценить",
    "TEST_EXCEL": "Отчет менеджера",
    "GET_ALL_ORDERS_AGENT": "↙️ Мои заказы",
    "GET_ALL_TEXT": "Выберите один из дополнительных подтвержденных или неподтвержденных заказов.",
    "CONFIRMED_AGENT_ORDERS": "✅ Подтвержденный",
    "UNCONFIRMED_AGENT_ORDERS": "❓ Не подтверждено",
    'NOT_CONFIRMED_TEXT': "Неподтвержденные заказы",
    "CONFIRMED_TEXT": "Подтвержденные заказы",
    'NAME_MEMBER': "Ф.И.О",
    "MEMBER_PHONE": "Номер телефона",
    'DISTRICT_UPDATE': "Изменить провинцию",
    "DOCTOR_TYPE": "Работа",
    'UPDATE_USER_DATA': 'Изменить имя',
    'UPDATE_USER_DATA_LAST_NAME': 'Изменить фамилия',
    'UPDATE_PHONE_NUMBER': 'Изменить номер телефона',
    'CREATE_USER_PHONE_NUMBER': "Введите номер телефона",
    'CREATE_USER_NAME': "Введите имя сотрудника",
    'CREATE_USER_LAST_NAME': "Введите фамилию сотрудника",
    "NOT_PLUS": "Начните номер с «+», например +998900123456, попробуйте еще раз",
    "NOT_LENGTH": "Вводимый символ не содержит 13 символов. Повторите попытку.",
    'NOT_INT': "Вы вводите другую информацию, пожалуйста, введите правильную информацию",
    'VIZIT_DOCUMENT_MANAGER_TEXT': "Выберите отчеты о местоположении или посещениях",
    'MANAGER_DOCUMENT': 'Отчет о посещении',
    'MANAGER_LOCATION': 'Отчет о местоположении',
    'WORKERS': "Список рабочих",
    'BAD_REQUEST_PRODUCT': "Нет в наличии, попробуйте еще раз",
    'FILE_NOT_FOUND': "Файл не найден",
    'READ_OR_CREATE': "Вы хотите добавить или загрузить новый?",
    'CREATE_CONTRACT_NUMBER': "Eksel Yaratish",
    'READ_CONTRACT_NUMBER': 'Eksel Yuklash',
    'CREATE_CONTRACT_NUMBER_TEXT': 'Отбросьте ось номера контракта',
    "ADMIN_VIZIT_REPORT": "Отчеты о посещениях М/П",
    'CREATE_DIRECTOR_NAME': 'Введите имя и фамилию руководителя предприятия (аптеки)',
    'CREATE_PROVIDER_PHONE_NUMBER': 'Введите номер телефона заместителя руководителя предприятия (аптеки)',
    'CREATE_DIRECTOR_PHONE_NUMBER': 'Введите номер телефона руководителя предприятия (Аптеки)',
    'CREATE_PROVIDER_NAME': 'Введите имя и фамилию заместителя руководителя предприятия (аптеки)',
    'DIRECTOR_NAME': "Имя директора",
    'DIRECTOR_PHONE_NUMBER': "Телефон директора",
    'PROVIDER_NAME': "Имя помощника",
    'PROVIDER_PHONE_NUMBER': "Телефон поддержки",
    'CHECK_CREATE_BOSSES': 'Информация верна ?',
    'CANCEL_BOSSES_UPDATED': 'Не изменено, вы отказались',
    'SUCCESS_BOSSES_UPDATED': 'Информация руководителей предприятия (Аптеки) успешно изменена.',
    "BAD_REQUEST": "Пожалуйста, введите правильную информацию, она не будет работать правильно, пока вы не введете номер.",
    'EXCEL_FILE': 'Пожалуйста, вы можете просмотреть файл Excel'
}
